<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { errorMessage, formatDate, formatCredits } from "../format";
import type { AdminBridge, JsonRecord } from "../types";
const props=defineProps<{bridge:AdminBridge}>(); const rows=ref<JsonRecord[]>([]); const created=ref<JsonRecord[]>([]); const busy=ref(false); const form=reactive({count:1,credits:"1.0000",expires_at:""});
async function load(){rows.value=await props.bridge.api("/api/v1/admin/redeem-codes")}
async function create(){busy.value=true; try {created.value=await props.bridge.api("/api/v1/admin/redeem-codes",{method:"POST",body:JSON.stringify({count:Number(form.count),credits:form.credits,expires_at:form.expires_at||null})}); await load(); props.bridge.toast("兑换码已生成，请立即复制明文")}catch(e){props.bridge.toast(errorMessage(e))}finally{busy.value=false}}
async function disable(id:string){if(!confirm("确定停用该兑换码？"))return; try{await props.bridge.api(`/api/v1/admin/redeem-codes/${encodeURIComponent(id)}/disable`,{method:"POST"});await load()}catch(e){props.bridge.toast(errorMessage(e))}}
onMounted(load);
</script>
<template><div class="page-head"><div><h1>兑换码管理</h1><p>生成一次性余额兑换码并管理状态。</p></div></div><section class="panel"><form class="grid three" @submit.prevent="create"><div class="field"><label>数量</label><input v-model.number="form.count" type="number" min="1" max="1000" required></div><div class="field"><label>每码额度</label><input v-model="form.credits" required></div><div class="field"><label>过期时间（可选）</label><input v-model="form.expires_at" type="datetime-local"></div><button class="primary-btn" type="submit" :disabled="busy">{{busy?'生成中…':'批量生成'}}</button></form></section><section v-if="created.length" class="panel"><h2>本次生成的明文（仅显示一次）</h2><div class="table-wrap"><table><tbody><tr v-for="item in created" :key="item.code_id"><td class="mono">{{item.code}}</td><td>{{formatCredits(item.credits)}}</td></tr></tbody></table></div></section><section class="panel"><h2>兑换码列表</h2><div v-if="!rows.length" class="empty">暂无兑换码。</div><div v-else class="table-wrap"><table><thead><tr><th>提示</th><th>额度</th><th>状态</th><th>创建时间</th><th>操作</th></tr></thead><tbody><tr v-for="item in rows" :key="item.id || item.code_id"><td class="mono">{{item.code_hint}}</td><td>{{formatCredits(item.credits || Number(item.credit_units)/10000)}}</td><td>{{item.status}}</td><td>{{formatDate(item.created_at)}}</td><td><button v-if="item.status==='active'" class="danger-btn" @click="disable(item.id || item.code_id)">停用</button></td></tr></tbody></table></div></section></template>
